// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Document struct {
	ID      int64
	Title   string
	OwnerID int64
}

type DocumentAccess struct {
	DocumentID int64
	UserID     int64
}

type Page struct {
	DocumentID int64
	PageNumber int16
	Content    string
}

type User struct {
	ID       int64
	Username string
}
