// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (title, owner_id)
VALUES ($1, $2)
RETURNING id
`

type CreateDocumentParams struct {
	Title   string
	OwnerID int64
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDocument, arg.Title, arg.OwnerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM page
WHERE document_id = $1 AND page_number = $2
`

type DeletePageParams struct {
	DocumentID int64
	PageNumber int16
}

func (q *Queries) DeletePage(ctx context.Context, arg DeletePageParams) error {
	_, err := q.db.ExecContext(ctx, deletePage, arg.DocumentID, arg.PageNumber)
	return err
}

const getDocument = `-- name: GetDocument :many
SELECT d.id, d.title, d.owner_id, u.username, p.page_number, p.content
FROM documents d
INNER JOIN users u ON d.owner_id = u.id
LEFT JOIN page p ON d.id = p.document_id
WHERE d.id = $1 and (
    d.owner_id = $2 OR EXISTS (
        SELECT 1
        FROM document_access da
        WHERE da.user_id = $2 AND da.document_id = d.id
    )
)
ORDER BY p.page_number ASC
`

type GetDocumentParams struct {
	ID      int64
	OwnerID int64
}

type GetDocumentRow struct {
	ID         int64
	Title      string
	OwnerID    int64
	Username   string
	PageNumber sql.NullInt16
	Content    sql.NullString
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) ([]GetDocumentRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocument, arg.ID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentRow
	for rows.Next() {
		var i GetDocumentRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OwnerID,
			&i.Username,
			&i.PageNumber,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocuments = `-- name: GetDocuments :many
SELECT d.id, d.title, d.owner_id, u.username, pages.c
FROM documents d
INNER JOIN users u ON d.owner_id = u.id
LEFT JOIN LATERAL (
    SELECT count(*) AS c FROM page WHERE document_id = d.id
) pages ON true
WHERE d.owner_id = $1 OR EXISTS (
    SELECT 1
    FROM document_access da
    WHERE da.user_id = $1 AND da.document_id = d.id
)
ORDER BY d.id DESC
`

type GetDocumentsRow struct {
	ID       int64
	Title    string
	OwnerID  int64
	Username string
	C        int64
}

func (q *Queries) GetDocuments(ctx context.Context, ownerID int64) ([]GetDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocuments, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentsRow
	for rows.Next() {
		var i GetDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OwnerID,
			&i.Username,
			&i.C,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPage = `-- name: GetPage :one
SELECT document_id, page_number, content
FROM page p
WHERE p.document_id = $1 AND p.page_number = $2
`

type GetPageParams struct {
	DocumentID int64
	PageNumber int16
}

func (q *Queries) GetPage(ctx context.Context, arg GetPageParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPage, arg.DocumentID, arg.PageNumber)
	var i Page
	err := row.Scan(&i.DocumentID, &i.PageNumber, &i.Content)
	return i, err
}
