// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (title, owner_id)
VALUES ($1, $2)
RETURNING id
`

type CreateDocumentParams struct {
	Title   string
	OwnerID int64
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDocument, arg.Title, arg.OwnerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPage = `-- name: CreatePage :exec
INSERT INTO page (document_id, page_number, content)
    VALUES ($1, $2, '')
`

type CreatePageParams struct {
	DocumentID int64
	PageNumber int16
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) error {
	_, err := q.db.ExecContext(ctx, createPage, arg.DocumentID, arg.PageNumber)
	return err
}

const getDocument = `-- name: GetDocument :many
SELECT d.id, d.title, d.owner_id, u.username, p.page_number, p.content
FROM documents d
INNER JOIN users u ON d.owner_id = u.id
LEFT JOIN page p ON d.id = p.document_id
WHERE d.id = $1 and (
    d.owner_id = $2 OR EXISTS (
        SELECT 1
        FROM document_access da
        WHERE da.user_id = $2 AND da.document_id = d.id
    )
)
ORDER BY p.page_number ASC
`

type GetDocumentParams struct {
	ID      int64
	OwnerID int64
}

type GetDocumentRow struct {
	ID         int64
	Title      string
	OwnerID    int64
	Username   string
	PageNumber sql.NullInt16
	Content    sql.NullString
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) ([]GetDocumentRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocument, arg.ID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentRow
	for rows.Next() {
		var i GetDocumentRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OwnerID,
			&i.Username,
			&i.PageNumber,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocuments = `-- name: GetDocuments :many
SELECT d.id, d.title, d.owner_id, u.username, pages.c
FROM documents d
INNER JOIN users u ON d.owner_id = u.id
LEFT JOIN LATERAL (
    SELECT count(*) AS c FROM page WHERE document_id = d.id
) pages ON true
WHERE d.owner_id = $1 OR EXISTS (
    SELECT 1
    FROM document_access da
    WHERE da.user_id = $1 AND da.document_id = d.id
)
ORDER BY d.id DESC
`

type GetDocumentsRow struct {
	ID       int64
	Title    string
	OwnerID  int64
	Username string
	C        int64
}

func (q *Queries) GetDocuments(ctx context.Context, ownerID int64) ([]GetDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocuments, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentsRow
	for rows.Next() {
		var i GetDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OwnerID,
			&i.Username,
			&i.C,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putTitle = `-- name: PutTitle :exec
UPDATE documents
SET title = $1
WHERE id = $2 AND (
    owner_id = $3 OR
    EXISTS (
        SELECT 1
        FROM document_access
        WHERE user_id = $3 AND document_id = $2
    )
)
`

type PutTitleParams struct {
	Title   string
	ID      int64
	OwnerID int64
}

func (q *Queries) PutTitle(ctx context.Context, arg PutTitleParams) error {
	_, err := q.db.ExecContext(ctx, putTitle, arg.Title, arg.ID, arg.OwnerID)
	return err
}

const updatePageNumbers = `-- name: UpdatePageNumbers :exec
UPDATE page
SET page_number = page_number + 1
WHERE document_id = $1 AND page_number >= $2
`

type UpdatePageNumbersParams struct {
	DocumentID int64
	PageNumber int16
}

func (q *Queries) UpdatePageNumbers(ctx context.Context, arg UpdatePageNumbersParams) error {
	_, err := q.db.ExecContext(ctx, updatePageNumbers, arg.DocumentID, arg.PageNumber)
	return err
}

const validateAccess = `-- name: ValidateAccess :one
SELECT 1
FROM documents d
WHERE d.id = $2 AND (
    d.owner_id = $1 OR EXISTS (
        SELECT 1
        FROM document_access
        WHERE document_id = $2 AND user_id = $1
    )
)
`

type ValidateAccessParams struct {
	OwnerID int64
	ID      int64
}

func (q *Queries) ValidateAccess(ctx context.Context, arg ValidateAccessParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, validateAccess, arg.OwnerID, arg.ID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
